@REM cd D:\ICS4U\TypingGame
@REM SET DOTNET_ROOT=D:\ICS4U\dotnetSDK\dotnet.exe
@REM SET DOTNET_MULTILEVEL_LOOKUP=0
@REM SET PATH=D:\ICS4U\dotnetSDK\dotnet.exe;%PATH%
@REM code .
@REM WORK IN PROGRESS TO GET THIS WORKING ON SCHOOL COMPUTERS
cd D:\ICS4U\TypingGame

SET DOTNET_ROOT=D:\ICS4U\dotnetSDK

SET DOTNET_MULTILEVEL_LOOKUP=0

SET PATH=D:\ICS4U\dotnetSDK;%PATH%

code .